server:
  # all REST services have prefix /spring-boot-flyway-sample
  contextPath: /spring-boot-flyway-sample
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false
    hibernate:
      ddl-auto: none
