CREATE TABLE ADDRESS (
  ID     BIGINT      NOT NULL AUTO_INCREMENT,
  STREET VARCHAR(60) NOT NULL,
  PHONE  VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE (
  ID          BIGINT      NOT NULL AUTO_INCREMENT,
  FIRST_NAME  VARCHAR(60) NOT NULL,
  LAST_NAME   VARCHAR(40) NOT NULL,
  DESCRIPTION VARCHAR(60) NOT NULL,
  ADDRESS_ID  BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);

INSERT INTO ADDRESS (ID, STREET, PHONE) VALUES
  (1, 'Bozhenko', '044-111-11-11');

INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, DESCRIPTION, ADDRESS_ID) VALUES
  (1, 'Ivan', 'Ivanov', 'Ivan Ivanov is Java Dev.', 1),
  (2, 'Petro', 'Petrov', 'Petro Petrov is Scala Dev.', NULL);